[package]
name = "mcr"
version = "0.1.4"
description = "A modular C++23 package"
license = "MIT"

[lib]
path = "src/mcr.cppm"

[dependencies.compat]
curl = "8.21.0"

[target.linux.dependencies.compat]
openssl = "3.5.1"

[target.linux.build]
defines = ["MCR_SSL_CTX_OPENSSL"]

[target.macos.dependencies.compat]
openssl = "3.5.1"

[target.macos.build]
defines = ["MCR_SSL_CTX_OPENSSL"]
