// hello — generated by `mcpp new`
import std;

int main(int argc, char* argv[]) {
    std::println("Hello from hello!");
    std::println("Built with import std + std::println on modular C++23.");
    if (argc > 1) {
        for (int i = 1; i < argc; ++i) std::println("  arg[{}] = {}", i, argv[i]);
    }
    return 0;
}
